version: "3.7"
services:
  database:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=vignesh
      - MYSQL_DATABASE=nec_trader_db
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    networks:
      - default
    ports:
      - "7070:7070"
volumes:
  data: