basePath: /
definitions:
  models.Trader:
    properties:
      doj:
        type: string
      traderId:
        type: integer
      traderName:
        type: string
    type: object
host: localhost:7070
info:
  contact:
    email: param@swagger.io
    name: API Support
  description: This is a sample service for managing Traders
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Traders API
  version: "1.0"
paths:
  /traders:
    get:
      consumes:
      - application/json
      description: Get details of all traders
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Trader'
            type: array
      summary: Get details of all traders
      tags:
      - traders
    post:
      consumes:
      - application/json
      description: Create a new trader with the input paylod
      parameters:
      - description: Create trader
        in: body
        name: trader
        required: true
        schema:
          $ref: '#/definitions/models.Trader'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Trader'
      summary: Create a new trader
      tags:
      - traders
  /traders/{traderId}:
    delete:
      consumes:
      - application/json
      description: Delete the trader corresponding to the input traderId
      parameters:
      - description: ID of the trader to be deleted
        in: path
        name: traderId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Delete trader identified by the given traderId
      tags:
      - traders
    get:
      consumes:
      - application/json
      description: Get details of order corresponding to the input traderId
      parameters:
      - description: ID of the trader
        in: path
        name: traderId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Trader'
      summary: Get details for a given traderId
      tags:
      - traders
    post:
      consumes:
      - application/json
      description: Update the trader corresponding to the input traderId
      parameters:
      - description: ID of the trader to be updated
        in: path
        name: traderId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Trader'
      summary: Update trader identified by the given traderId
      tags:
      - traders
swagger: "2.0"
